# Generated by Django 4.0.1 on 2022-01-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyname', models.CharField(default='', max_length=255)),
                ('finescount', models.IntegerField(default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacistname', models.CharField(default='', max_length=255)),
                ('birthday', models.CharField(default='', max_length=10)),
                ('licensenumber', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionname', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('pharmaciescount', models.IntegerField(default=0, max_length=4)),
            ],
        ),
    ]
